name: Test

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build

      - name: 'Simple'
        uses: ./
        with:
          frevo_token: ${{ secrets.FREVO_TOKEN_1 }}
          path: './fixture/1-petstore/openapi.json'

      - name: 'Unbundled'
        uses: ./
        with:
          frevo_token: ${{ secrets.FREVO_TOKEN_2 }}
          path: './fixture/2-petstore-ref/openapi.yaml'

      # - name: 'Stripe'
      #   uses: ./
      #   with:
      #     frevo_token: 'test'
      #     path: './fixture/3-stripe/openapi.json'
