name: Test

on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build

      - name: "1"
        uses: ./
        with:
          frevo_token: "test"
          path: "./fixture/1-petstore/openapi.json"

      - name: "2"
        uses: ./
        with:
          frevo_token: "test"
          path: "./fixture/2-petstore-ref/openapi.yaml"
